node.name: es01
cluster.name: es-docker-cluster
discovery.type: single-node
bootstrap.memory_lock: true
xpack.security.http.ssl.enabled: false
xpack.security.enabled: true
network.host: 0.0.0.0
http.host: 0.0.0.0