version: '3.8'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      HOSTS: '["http://host.docker.internal:${ELASTICSEARCH_PORT}"]'
      USER: ${USER}
      PASSWORD: ${PASSWORD}
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    privileged: true