version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=${PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
    volumes:      
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata1:/usr/share/elasticsearch/data   
    
volumes:
  esdata1:
    driver: local

networks:
  esnet:
    # driver: bridge

#     version: '3.8'
# services:
#   es01:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
#     container_name: es01
#     environment:
#       - node.name=es01
#       - cluster.name=es-docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - xpack.security.enabled=true
#       - xpack.security.http.ssl.enabled=false
#       - ELASTIC_PASSWORD=${MSL_PASSWORD}
#       - discovery.seed_hosts=es02,es03
#       - cluster.initial_master_nodes=es01,es02,es03
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - "9200:9200"
#     volumes:
#       - esdata1:/usr/share/elasticsearch/data

#   es02:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
#     container_name: es02
#     environment:
#       - node.name=es02
#       - cluster.name=es-docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - xpack.security.enabled=true
#       - xpack.security.http.ssl.enabled=false
#       - discovery.seed_hosts=es01,es03
#       - cluster.initial_master_nodes=es01,es02,es03
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - "9201:9200"
#     volumes:
#       - esdata2:/usr/share/elasticsearch/data

#   es03:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
#     container_name: es03
#     environment:
#       - node.name=es03
#       - cluster.name=es-docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - xpack.security.enabled=true
#       - xpack.security.http.ssl.enabled=false
#       - discovery.seed_hosts=es01,es02
#       - cluster.initial_master_nodes=es01,es02,es03
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - "9202:9200"
#     volumes:
#       - esdata3:/usr/share/elasticsearch/data

# volumes:
#   esdata1:
#     driver: local
#   esdata2:
#     driver: local
#   esdata3:
#     driver: local