server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: ${HOSTS}
monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.username: ${USER}
elasticsearch.password: ${PASSWORD}